occmundial/atomic

lib/components/TextField/index.test.tsx
lib/components/TextField/index.tsx
lib/components/TextField/styles.ts

Port changes from old atomic, to include searchField prop
- Added searchField prop
- Added required styles
- Adjusted icon sizes like old atomic

feat: Add searchField prop

---

.gitignore
lib/components/Autocomplete/index.tsx

- Pass ref using forwardRef
- Adjust default props
- Adjust showDroplist condition
- Add tsconfig.buildinfo to gitignore

feat: Add Ref to Autocomplete field

---

lib/components/Tag/index.tsx
lib/components/Tag/styles.ts

Add new variant color for Tag component `primary`

feat: Add new Tag color theme

---

lib/components/OrderBy/index.tsx

- Update labels to show a strong color for the selected filter
- Update icon color to grey800 to match design

feat: Update orderBy labels

---

lib/components/Footer/List/index.tsx
lib/components/Footer/List/styles.ts
lib/components/Footer/index.tsx
lib/components/Footer/styles.ts

- Change footer text to be darker https://app.zeplin.io/project/5d5ae14f0b1ec53e16818628/screen/62b354c3e4e1301a91d11148

Change footer font color

---

lib/components/Pager/Page/styles.ts
lib/components/Pager/index.tsx
lib/components/Pager/styles.ts

Added changes on visuals for pager.
PREVIEW
- First value 
- Middle value 
- Last value

feat: Pager changes

---

lib/components/Pager/index.tsx
lib/components/Pager/styles.ts

feat: Add margins when numbers are hidden

---

lib/components/TextField/index.tsx

Change icon used in password Texfield.
**Before:**
**After:**

Change password icon

---

lib/components/Droplist/index.tsx
lib/components/Droplist/styles.ts

Drop List element

---

lib/components/Radio/index.tsx

Se añade el property de testId al componente del radio button para la creación de pruebas automatizadas.

feat: Add testId to radio button component

---

lib/components/Button/index.tsx
src/docs/Button.mdx

- Added name prop
- Added value prop
- Updated docs
These new props are usefull when implementing buttons on HTML `forms`

feat: Add new props to button

---

src/components/Tooltip/index.tsx

Improve code readability and arrow color constant naming

fix: Code readability in the tooltip class and arrow color constant

---

src/docs/Tooltip.mdx

Updated the default value for closeDelay to 4000 and removed the warning, success, and error themes.

feat: Added fit property to documentation

---

package.json
src/components/MDXComponents.ts
src/components/Tooltip/hooks.ts
src/components/Tooltip/index.tsx
src/components/Tooltip/styles.ts
src/docs/Tooltip.mdx
src/hooks/useThrottle.ts
yarn.lock

[screen-recording (5).webm](https://github.com/occmundial/atomic/assets/120593690/4a87390f-884c-464e-81fc-692ef032f728)

feat: Tooltip Component beta

---

lib/components/SlideDown/index.tsx

Se agrega popiedad `noJustified` a componente <SlideDown/>

feat: Add noJustified to SlideDown Component

---

lib/components/Modal/index.tsx

- Se agrega la propiedad type a los botones de modal

feat: Aff type button in modal

---

lib/components/Button/styles.ts
lib/tokens/fonts.ts
styles/globals.css

Rebranding on atomic beta FONT

---

lib/components/Button/styles.ts
lib/tokens/fonts.ts
styles/globals.css

Add new FONT to atomic main

---

lib/components/Button/styles.ts
lib/components/Pager/styles.ts
lib/components/Tag/styles.ts
lib/components/Text/styles.ts
lib/components/TextField/index.tsx
lib/components/TextField/styles.ts
lib/components/Tooltip/styles.ts

New font styles

---

lib/components/Button/index.tsx
lib/components/Button/styles.ts

refactor: Remove unused imports

fix: Make Button theme optional

---

lib/components/Text/styles.ts
src/docs/Text.mdx

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%201?workitem=27492
Updated Text component documentation , more info of prop changes in https://occmundialmx-my.sharepoint.com/:w:/g/personal/ryanez_occ_com_mx/EWK-7nSFg4NLiY1tZd0N-C0BAtMf5mw7pF8wW17A31Xwrg?e=yyN9Ce

feat: Updated Text component documentation

---

lib/tokens/future/fonts.json

Update design tokens

---

lib/components/Text/styles.ts

Replaced new font family var with old one

fix: Replaced new font family var with old one

---

.babelrc
jest.config.js
lib/components/Button/styles.ts
lib/components/Text/helper.ts
lib/components/Text/index.tsx
lib/components/Text/styles.ts
lib/utils/font.ts
tsconfig.json
tsconfig.lib.json

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%201?workitem=28488
- Fixed the font name issue in the button
- Created a utils folder to allow to refactor objectToFontValue function
- Refactored classTranslation to the helper folder

Fix button font

---

lib/components/Radio/index.tsx
lib/components/Radio/styles.ts
src/components/MDXComponents.ts
src/docs/Radio.mdx

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%202?workitem=28865
https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%202?workitem=28867
https://www.figma.com/file/T5ldwkRZl9mMSa11aYHNZ5/Form-Elements?type=design&node-id=43-1521&mode=design&t=1KX0t47axxlpNoSX-0
- Updated Radio component design
- Created Radio component documentation

Radio update

---

lib/components/Droplist/index.tsx
lib/components/Droplist/styles.ts
src/components/MDXComponents.ts
src/docs/Droplist.mdx

Update droplist styles with new design tokens

---

lib/components/Tooltip/index.tsx
src/docs/Tooltip.mdx

- Fixed flip and autoUpdate prop types
- Fixed a bug that causes arrow not showing in flip

fix: Type issues

---

lib/components/Toggle/index.tsx
lib/components/Toggle/styles.ts
src/components/MDXComponents.ts
src/docs/Toggle.mdx

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%203?workitem=29603
https://www.figma.com/design/T5ldwkRZl9mMSa11aYHNZ5/Form-Elements?node-id=452-4640&t=WawG7gKjZrWAOpFY-0
Updated tooltip appearance.
Developed documentation for tooltips.

feat: Updated toogle component and documentation

---

lib/components/Pill/Choice/index.tsx
lib/components/Pill/Choice/styles.ts
lib/components/Pill/Group/index.tsx
lib/components/Pill/Group/styles.ts
lib/components/Pill/Stack/index.tsx
lib/components/Pill/Stack/styles.ts
lib/components/Pill/index.tsx
lib/components/Pill/styles.ts
src/components/MDXComponents.ts
src/components/Pill/Choice/index.tsx
src/components/Pill/Group/index.tsx
src/components/Pill/Stack/index.tsx
src/docs/Pill.mdx

[Azure Task 29721](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%203?workitem=29721)

Update pill styles with design tokens

---

lib/components/Tooltip/Tip/BeakIcon.tsx
lib/components/Tooltip/Tip/index.tsx
lib/components/Tooltip/Tip/styles.ts
lib/components/Tooltip/helper.ts
lib/components/Tooltip/index.tsx

- Update arrow to adjust to new design
- Added out to tooltip in purple and dark theme

feat: Update tooltip styles and dummy

---

lib/components/Tag/index.tsx
lib/components/Tag/styles.ts
src/docs/Tag.mdx

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%205?workitem=30430
https://www.figma.com/design/u4GPoRpEziZC1svzeyLEus/Tags?node-id=2-3513&t=nix4B3FgeTeGsCWB-0
Updated tag design and documentation

feat: Tag design and dcumentation updated

---

lib/components/Alert/AlertText/index.tsx
lib/components/Alert/index.test.tsx
lib/components/Alert/index.tsx
lib/components/Alert/styles.ts
src/components/Alert/Small/index.tsx
src/components/MDXComponents.ts
src/docs/Alert.mdx

[Azure Task 30389](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%204?workitem=30389)

feat: Update alert with new design tokens and add new props

---

lib/components/Alert/index.tsx
lib/components/Alert/styles.ts
src/components/Alert/Small/index.tsx
src/docs/Alert.mdx

[Azure Bug 31929](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=31929)

fix: Add hover styles to alert link action

---

lib/components/Tag/styles.ts

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=32083
Changed outlines to borders.

fix: Changed tag border to outline

---

lib/components/Tag/index.tsx
lib/components/Tag/styles.ts

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=32154
Remove extra padding in the label

fix: Remove extra padding in label

---

lib/components/Alert/index.tsx

[Azure Task 32403](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%206?workitem=32403)

fix: Change icon close size to md

---

lib/components/Footer/index.tsx
lib/components/Footer/styles.ts
lib/components/Grid/Col/styles.ts
lib/components/Grid/Row/styles.ts
lib/components/Grid/styles.ts
lib/tokens/grid.ts
src/components/Content/index.tsx
src/components/Grid/index.tsx
src/components/MDXComponents.ts
src/docs/Grid.mdx

[Azure Task 32771](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%207?workitem=32771)

feat: Update grid with new design tokens

---

lib/components/Tooltip/index.tsx
lib/components/Tooltip/styles.ts
src/docs/Tooltip.mdx

[Azure Task 33060](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%207?workitem=33060)

feat: Update tooltip with new design tokens

---

lib/components/SlideDown/index.tsx
lib/components/SlideDown/styles.ts
src/components/MDXComponents.ts
src/components/SlideDown/index.tsx
src/docs/SlideDown.mdx

[Azure Task 33522](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%208?workitem=33522)

Update slidedown with new design tokens

---

lib/components/Pill/Choice/index.tsx
lib/components/Pill/Group/index.tsx
lib/components/Pill/Stack/index.tsx

Added attribute type=button to pillś buttons

feat: Added attribute type button to buttons

---

lib/components/TextField/index.tsx

- Add type="button" on eye icon for password type on text field, to avoid form submision on clients like scooby that uses HTML forms

feat: Add type button to eye icon

---

lib/components/Logo/index.tsx
lib/components/NavIcon/index.tsx
lib/components/NavIcon/styles.ts
lib/components/NavItem/styles.ts
lib/components/NavTab/index.tsx
lib/components/NavTab/styles.ts
lib/components/NavTop/styles.ts

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%2010?workitem=34649
- Updated styles for NavIcon, NavItem, NavTab, and NavTop.
- Corrected the incorrect white token in the Logo component.

feat: Updated header styles

---

lib/components/List/index.tsx
lib/components/List/styles.ts
lib/components/ListItem/index.tsx
lib/components/ListItem/styles.ts
lib/components/ListItemAvatar/index.tsx
lib/components/ListItemAvatar/styles.ts
lib/components/ListItemButton/index.tsx
lib/components/ListItemButton/styles.ts
lib/components/ListItemIcon/index.tsx
lib/components/ListItemIcon/styles.ts
lib/components/ListItemText/index.tsx
lib/components/ListItemText/styles.ts
lib/components/ListProvider/index.tsx
lib/components/NavTab/index.tsx
lib/components/Text/index.tsx
src/components/MDXComponents.ts
src/docs/List.mdx

https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%2010?workitem=35158
Added basic List documentation
Added List, ListProvider, ListItem, ListItemButton, ListItemAvatar, ListItemIcon components based mostly in https://mui.com/material-ui/react-list/

feat: Added list element and basic examples

---

lib/components/Dropdown/index.tsx
lib/components/Dropdown/styles.ts
lib/components/NavAvatarButton/index.tsx
lib/components/index.ts
src/components/MDXComponents.ts
src/components/MenuDropdown/index.tsx
src/docs/Dropdown.mdx
src/docs/NavTab.mdx

[Azure Task 35711](https://dev.azure.com/occmundial/Proyectos/_sprints/taskboard/Expert%20Team/Proyectos/ET%20-%20Sprint%2010?workitem=35711)

feat: Create dropdown component for header purpose

---

.gitignore
catalog-info.yaml

* Add information to set the ct tokens
* ignore ide folder

Add information to set the ct tokens

---

.gitignore
src/utils/scope.ts

feat: Add new ct colors
